### ISSUE TITLE
Support tinycc

### ISSUE THREAD

**Issue by star-hengxing** [xmake-io/xmake.sh#6]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

N/A

**Comment by waruqi** [comment]
话说为啥需要用到 tinycc 呢，要支持的话

可以在这里扩展一路 toolchain https://github.com/xmake-io/xmake.sh/blob/a10ae2f58fbf3ba2fa7a4646c383d81fd8d9b79f/configure#L3040

然后就是跟着 case 判断下就行了 https://github.com/xmake-io/xmake.sh/blob/a10ae2f58fbf3ba2fa7a4646c383d81fd8d9b79f/configure#L391

可以直接提个 pr 过来

**Comment by star-hengxing** [comment]
这样可以只用 shell + tinycc 构建 xmake，可以简化一些 boostrap 环境。

这个 shell 写的脚本试了一下，卡在链接了（shell 有点难学。。）因为 tcc 需要传 -ar cr flags

**Comment by waruqi** [comment]
> 这样可以只用 shell + tinycc 构建 xmake，可以简化一些 boostrap 环境。

可以是可以，不过 tinycc 构建出来的 binary 也不是最优的，如果实际使用 还是走 gcc/clang 编译，运行效率最高把

**Comment by waruqi** [comment]
支持了，不过目前也就 linux 上可以，macos 上 tcc 暂时无法找到 stdio 等库。

```console
./configure --toolchain=tinycc; make VERBOSE=1 -j4

XMAKE_PROGRAM_DIR=/mnt/xmake/xmake/ ./build/xmake --version
xmake v2.9.6+dev.1fd6cff94, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io
    
    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

```
